title: Backnol Yogendran Blog
email: backnol@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Backnol's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: backnol
github_username:  backnol

# Build settings
theme: texture
plugins:
  - jekyll-feed
  - jekyll-seo-tag

texture:
  title: Backnol Yogendran
  tagline: 
  date_format: "%b %-d, %Y"
  style: blue

  social_links:
    twitter: backnol
    github:  backnol
    linkedIn: in/backnol # format: locale/username
